# Images and buildconfig definitions for tensorflow docker images
apiVersion: v1
kind: ImageStream
metadata:
  name: "archlinux-base"
  annotations:
    tags: "infrastructure,os,archlinux,base-image,docker"
    openshift.io/display-name: "ArchLinux"
    openshift.io/provider-display-name: "https://archlinux.org"
spec:
  imagePullPolicy: IfNotPresent
  tags:
    - name: "latest"
      annotations:
        openshift.io/display-name: "ArchLinux"
        openshift.io/provider-display-name: "https://archlinux.org"
      from:
        kind: "DockerImage"
        name: "archlinux/base:latest"
      referencePolicy:
        type: "Local"


