# Custom images build configs
---
apiVersion: v1
kind: ImageStream
metadata:
  name: "tensorflow-base-cpu"
  annotations:
    tags: "tensorflow,cpu-optimized,base-image,python,docker"
    openshift.io/display-name: "Tensorflow base image (CPU optimized library)"
    openshift.io/provider-display-name: "HPE S.p.A."

---
apiVersion: v1
kind: BuildConfig
metadata:
  name: "tensorflow-base-cpu"
  annotations:
    tags: "tensorflow,cpu-optimized,base-image,python,docker"
    openshift.io/display-name: "Tensorflow base image (CPU optimized library)"
    openshift.io/provider-display-name: "HPE S.p.A."
# buildconfig spec: build image from git repository
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: http://github.com/mcaimi/dockerfiles.git
      ref: "master"
    contextDir: "tensorflow"
  strategy:
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "archlinux-base:latest"
      dockerFilePath: "tensorflow/dockerfiles/Dockerfile.tensorflow-base-cpu"
      noCache: false
      forcePull: false
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
  # Push built image into the embedded OpenShift registry
  output:
    to:
      kind: "ImageStreamTag"
      name: "tensorflow-base-cpu:latest"
